# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: PyPI

on:
  workflow_dispatch: ~
  release:
    types: [published]

env:
  DEFAULT_PYTHON: 3.9

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.DEFAULT_PYTHON }}

    - name: Install dependencies and build
      run: |
        pip install -U pip
        pip install build twine
        python -m build

    - name: Verify README
      # https://packaging.python.org/guides/making-a-pypi-friendly-readme/#validating-restructuredtext-markup
      run: |
        python -m twine check dist/*

    - name: Upload builds
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist

  pypi:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/PlexAPI
    permissions:
      id-token: write
    steps:
    - name: Download builds
      uses: actions/download-artifact@v5
      with:
        name: dist
        path: dist

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
